# Generated by Django 4.2.7 on 2023-11-10 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('nama_lengkap', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('alamat', models.TextField(blank=True, null=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('gambar_profil', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
