# Generated by Django 4.2.7 on 2023-11-10 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
